[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Engine/Maps/Templates/OpenWorld
EditorStartupMap=/Engine/Maps/Templates/OpenWorld
GlobalDefaultGameMode=/Script/FleetCommander.FCGameMode
GlobalDefaultServerGameMode=/Script/FleetCommander.FCGameMode
GameInstanceClass=/Script/Engine.GameInstance

[/Script/Engine.RendererSettings]
r.AllowStaticLighting=False
r.GenerateMeshDistanceFields=True
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.Shadow.Virtual.Enable=1
r.DefaultFeature.AutoExposure=False
r.DefaultFeature.MotionBlur=True
r.SkinCache.CompileShaders=True
r.DefaultFeature.Bloom=True
r.DefaultFeature.AmbientOcclusion=True

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
-D3D12TargetedShaderFormats=PCD3D_SM5
+D3D12TargetedShaderFormats=PCD3D_SM6

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[SystemSettings]
r.ScreenPercentage=100
r.Streaming.PoolSize=3000

; GTX 1050 Ti / low-end: set these instead
; r.ScreenPercentage=75
; r.Streaming.PoolSize=1800
; r.Lumen.DiffuseIndirect.Allow=0
; r.Lumen.Reflections.Allow=0
; r.Shadow.Virtual.Enable=0
